### ISSUE TITLE
Error: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by G07cha** [bcherny/tslint-no-circular-imports#18]
When a project has too many files `getAllCycles` eventually will hit the call stack size limit:

```
The 'no-circular-imports' rule threw an error in 'file.tsx':
RangeError: Maximum call stack size exceeded
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:195:30)
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:193:30)
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:193:30)
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:193:30)
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:193:30)
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:193:30)
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:193:30)
    at NoCircularImportsWalker.getAllCycles (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:193:30)
    at NoCircularImportsWalker.visitSourceFile (/Users/user/project/node_modules/tslint-no-circular-imports/noCircularImportsRule.js:102:34)
    at NoCircularImportsWalker.SyntaxWalker.visitNode (/Users/user/project/node_modules/tslint/lib/language/walker/syntaxWalker.js:482:22)
```

I've tried to refactor it so it will be asynchronus but it ran out of memory 😞 
Is there any way to make it work with large projects?

**Comment by bcherny** [comment]
How many files do you have? Any more info? Eg. Example dependency graph it’s crahsing on.

**Comment by G07cha** [comment]
Around 3590 excluding dependencies and it crashes on one of the project's files. I will try to create a script that will produce large amounts of files and will let you know if I run into the same issue on the generated project.

**Comment by G07cha** [comment]
@biolauri thanks for sharing this, 0.4.0 works for me as well! I believe the issue was introduced somewhere in  https://github.com/bcherny/tslint-no-circular-imports/commit/bada1af60b0f2316ea3197926a76e2e7f1e20531.

**Comment by JoshuaKGoldberg** [comment]
Switching from an iterative algorithm to a recursive algorithm comes with the risk of overflowing call stacks. Looks like there are two potential solutions here:

A. Switch back to an iterative algorithm
B. Introduce a depth limit

IMO both would be good. Having a depth limit would help with performance anyway.

**Comment by G07cha** [comment]
@JoshuaKGoldberg, thanks for your response and the work that you've put in! I initially thought that I could avoid call stack limits by using timeouts but then it ran out of memory 🤷‍♂️
